#!/bin/bash
# Auto-lint after file changes
# Generated by devtronic — generic version (auto-detects package manager)

# Only lint JS/TS source edits — skip docs/config/etc. so editing a README
# doesn't trigger a full (monorepo-wide) lint pass. Unknown input → proceed.
INPUT=$(cat 2>/dev/null)
FILE=$(printf '%s' "$INPUT" | node -e "let d='';process.stdin.on('data',c=>d+=c).on('end',()=>{try{process.stdout.write(JSON.parse(d).tool_input?.file_path||'')}catch(e){}})" 2>/dev/null)
case "$FILE" in
  "") ;; # couldn't determine the file — preserve prior behavior
  *.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs) ;; # lintable source
  *) exit 0 ;; # non-source edit — nothing to lint
esac

# Detect package manager
if [ -f "pnpm-lock.yaml" ]; then
  PM="pnpm"
elif [ -f "yarn.lock" ]; then
  PM="yarn"
elif [ -f "bun.lockb" ]; then
  PM="bun"
else
  PM="npm"
fi

RUN="$PM run"
if [ "$PM" != "npm" ]; then
  RUN="$PM"
fi

# Try lint:fix first, fall back to lint --fix
if node -e "const p=require('./package.json');process.exit(p.scripts?.['lint:fix']?0:1)" 2>/dev/null; then
  $RUN lint:fix -- --quiet 2>/dev/null || true
elif node -e "const p=require('./package.json');process.exit(p.scripts?.lint?0:1)" 2>/dev/null; then
  $RUN lint --fix --quiet 2>/dev/null || true
fi
