#!/bin/bash
# Auto-lint after file changes
# Generated by devtronic — generic version (auto-detects package manager)

# Detect package manager
if [ -f "pnpm-lock.yaml" ]; then
  PM="pnpm"
elif [ -f "yarn.lock" ]; then
  PM="yarn"
elif [ -f "bun.lockb" ]; then
  PM="bun"
else
  PM="npm"
fi

RUN="$PM run"
if [ "$PM" != "npm" ]; then
  RUN="$PM"
fi

# Try lint:fix first, fall back to lint --fix
if node -e "const p=require('./package.json');process.exit(p.scripts?.['lint:fix']?0:1)" 2>/dev/null; then
  $RUN lint:fix -- --quiet 2>/dev/null || true
elif node -e "const p=require('./package.json');process.exit(p.scripts?.lint?0:1)" 2>/dev/null; then
  $RUN lint --fix --quiet 2>/dev/null || true
fi
