#!/bin/bash
# Auto-checkpoint before context compaction
# Generated by devtronic

CHECKPOINT_DIR="thoughts/checkpoints"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

mkdir -p "$CHECKPOINT_DIR"

{
  echo "# Auto-checkpoint: $TIMESTAMP"
  echo ""
  echo "## Git Status"
  git diff --stat 2>/dev/null || echo "Not a git repo"
  echo ""
  echo "## Recent Commits"
  git log --oneline -5 2>/dev/null || echo "No commits"
} > "$CHECKPOINT_DIR/${TIMESTAMP}_pre-compact.md"

echo "Checkpoint saved: $CHECKPOINT_DIR/${TIMESTAMP}_pre-compact.md"

# Update persistent state (minimal — skill-level checkpoint writes richer state)
STATE_FILE="thoughts/STATE.md"
mkdir -p "$(dirname "$STATE_FILE")"
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
{
  echo "# Project State"
  echo ""
  echo "**Updated**: $(date '+%Y-%m-%d %H:%M') (auto-compact)"
  echo "**Branch**: $BRANCH"
  echo ""
  echo "## Last Auto-Checkpoint"
  echo ""
  echo "Context was compacted. See: \`$CHECKPOINT_DIR/${TIMESTAMP}_pre-compact.md\`"
  echo ""
  echo "## Recent Commits"
  echo ""
  git log --oneline -5 2>/dev/null || echo "No commits"
} > "$STATE_FILE"
