#!/bin/bash
# Quality gate: runs checks before allowing Claude to stop
# Generated by devtronic — generic version (auto-detects package manager)

INPUT=$(cat)

# Prevent infinite loops: if already triggered by a stop hook, allow stop
if echo "$INPUT" | grep -q '"stop_hook_active"'; then
  if echo "$INPUT" | grep -q '"stop_hook_active"[[:space:]]*:[[:space:]]*true'; then
    exit 0
  fi
fi

# Detect package manager
if [ -f "pnpm-lock.yaml" ]; then
  PM="pnpm"
elif [ -f "yarn.lock" ]; then
  PM="yarn"
elif [ -f "bun.lockb" ]; then
  PM="bun"
else
  PM="npm"
fi

RUN="$PM run"
if [ "$PM" != "npm" ]; then
  RUN="$PM"
fi

# Build quality command from available scripts
QUALITY_CMD=""
if node -e "const p=require('./package.json');process.exit(p.scripts?.typecheck?0:1)" 2>/dev/null; then
  QUALITY_CMD="$RUN typecheck"
fi
if node -e "const p=require('./package.json');process.exit(p.scripts?.lint?0:1)" 2>/dev/null; then
  if [ -n "$QUALITY_CMD" ]; then
    QUALITY_CMD="$QUALITY_CMD && $RUN lint"
  else
    QUALITY_CMD="$RUN lint"
  fi
fi

# If no quality scripts found, allow stop
if [ -z "$QUALITY_CMD" ]; then
  exit 0
fi

# Run quality checks
if ! eval "$QUALITY_CMD" > /dev/null 2>&1; then
  echo "Quality checks failed. Run '$QUALITY_CMD' to see details." >&2
  exit 2
fi

exit 0
