#!/bin/bash
# Quality gate: runs checks before allowing Claude to stop
# Generated by devtronic — generic version (auto-detects package manager)

INPUT=$(cat)

# Prevent infinite loops: if already triggered by a stop hook, allow stop
if echo "$INPUT" | grep -q '"stop_hook_active"'; then
  if echo "$INPUT" | grep -q '"stop_hook_active"[[:space:]]*:[[:space:]]*true'; then
    exit 0
  fi
fi

# --- Ownership signal: subordinate to an active convergence loop (FR-3) ---
# The sentinel lives in the worktree (relative path) so concurrent loops on
# different worktrees don't collide (FR-9).
STALE_SECS=900
if [ -f ".claude/.loop-owner" ]; then
  HB=$(grep -o '"heartbeat":[0-9]*' ".claude/.loop-owner" | grep -o '[0-9]*')
  NOW=$(date +%s)
  if [ -n "$HB" ] && [ $((NOW - HB)) -lt $STALE_SECS ]; then
    # Fresh: the loop is alive. Defer only while the machine owns a phase
    # mid-flight (not at a barrier — barriers require the gate to enforce).
    if grep -q '"owner":"machine"' ".claude/.loop-owner" && ! grep -q '"atBarrier":true' ".claude/.loop-owner"; then
      exit 0
    fi
  else
    # Stale: the loop died mid-phase. Reclaim for the human and enforce.
    rm -f ".claude/.loop-owner"
  fi
fi

# Detect package manager
if [ -f "pnpm-lock.yaml" ]; then
  PM="pnpm"
elif [ -f "yarn.lock" ]; then
  PM="yarn"
elif [ -f "bun.lockb" ]; then
  PM="bun"
else
  PM="npm"
fi

RUN="$PM run"
if [ "$PM" != "npm" ]; then
  RUN="$PM"
fi

# Build quality command from available scripts
QUALITY_CMD=""
if node -e "const p=require('./package.json');process.exit(p.scripts?.typecheck?0:1)" 2>/dev/null; then
  QUALITY_CMD="$RUN typecheck"
fi
if node -e "const p=require('./package.json');process.exit(p.scripts?.lint?0:1)" 2>/dev/null; then
  if [ -n "$QUALITY_CMD" ]; then
    QUALITY_CMD="$QUALITY_CMD && $RUN lint"
  else
    QUALITY_CMD="$RUN lint"
  fi
fi

# Manifest is the single source of truth for Tier ① gates when present.
if [ -f "loop.manifest.yaml" ]; then
  MANIFEST_CMD=$(devtronic loop --gate-cmd 2>/dev/null)
  if [ -n "$MANIFEST_CMD" ]; then
    QUALITY_CMD="$MANIFEST_CMD"
  fi
fi

# If no quality scripts found, allow stop
if [ -z "$QUALITY_CMD" ]; then
  exit 0
fi

# Run quality checks
if ! eval "$QUALITY_CMD" > /dev/null 2>&1; then
  echo "Quality checks failed. Run '$QUALITY_CMD' to see details." >&2
  exit 2
fi

exit 0
