#!/bin/bash
# Tells you when the project's devtronic files and the installed CLI have
# drifted apart. Generated by devtronic.
#
# Read-only and local: it reads two version strings and prints at most one
# line. It never fetches, never writes, and always exits 0 — a session must
# never fail to start because of this check.
#
# Detection only, on purpose. `devtronic update` deletes files the templates
# retired and asks about the ones you made yours, so it needs a human.

MANIFEST=".ai-template/manifest.json"
[ -f "$MANIFEST" ] || exit 0

# The version that last wrote this project's files. It is the first "version"
# key in the manifest; the per-file entries carry checksums, not versions.
PROJECT=$(grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' "$MANIFEST" 2>/dev/null \
  | head -1 | sed 's/.*"\([^"]*\)"$/\1/')
[ -n "$PROJECT" ] || exit 0

if command -v devtronic >/dev/null 2>&1; then
  CLI=$(devtronic --version 2>/dev/null)
elif command -v npx >/dev/null 2>&1; then
  CLI=$(npx --no-install devtronic --version 2>/dev/null)
fi
[ -n "$CLI" ] || exit 0

[ "$PROJECT" = "$CLI" ] && exit 0

# Which side is behind decides which command fixes it. If `sort -V` cannot
# order them, say what we know and let the human choose.
OLDEST=$(printf '%s\n%s\n' "$PROJECT" "$CLI" | sort -V 2>/dev/null | head -1)

if [ "$OLDEST" = "$PROJECT" ]; then
  echo "devtronic: this project was last written by $PROJECT, the CLI is $CLI. Run \`devtronic update\` to bring the project files in step."
elif [ "$OLDEST" = "$CLI" ]; then
  echo "devtronic: the CLI is $CLI but this project was written by $PROJECT. Run \`npm i -g devtronic@latest\` before updating anything."
else
  echo "devtronic: project $PROJECT, CLI $CLI — the two have drifted."
fi

exit 0
